import Intro from "@/components/Intro";
import Services from "@/components/Services";
import Head from "next/head";
import { data } from "./../data";

export default function Home({ services }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro />
      <Services services={services} />
    </div>
  );
}

export async function getStaticProps() {
  const services = data;
  return {
    props: {
      services,
    },
  };
}
