import Intro from "@/components/Intro";
import Services from "@/components/Services";
import Testimonials from "@/components/Testimonials";
import Head from "next/head";
import { data, users } from "./../data";

export default function Home({ services, usersItem }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="container"> */}
      <Intro />
      <Services services={services} />
      <Testimonials usersItem={usersItem} />
      {/* </div> */}
    </div>
  );
}

export async function getStaticProps() {
  const services = data;
  const usersItem = users;
  return {
    props: {
      services,
      usersItem,
    },
  };
}
